version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sdmedik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    restart: unless-stopped

  backend:
    build:
      context: .
      network: host  # Используем хост-сеть при сборке
    container_name: backend
    network_mode: host
    volumes:
      - ./image:/app/image
      - ./pkg/mailer/template:/app/template
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    network_mode: host
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

