name: Restrict Pull Request Merge

on:
  pull_request:
    branches:
      - main  # Срабатывает только для PR в main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR author and reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_AUTHOR=${{ github.event.pull_request.user.login }}  # Автор PR
          OWNER="fi44er"  # Замени на своё имя пользователя (владелец репозитория)

          # Проверяем, что автор PR — test
          if [ "$PR_AUTHOR" == "Valey88" ]; then
            echo "PR создан пользователем $PR_AUTHOR"

            # Проверяем, есть ли одобрение от владельца
            REVIEWS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/reviews" \
              | jq -r '.[] | select(.state == "APPROVED") | .user.login')

            if echo "$REVIEWS" | grep -q "$OWNER"; then
              echo "PR одобрен владельцем ($OWNER), слияние разрешено"
            else
              echo "Ошибка: PR от $PR_AUTHOR может быть смерджен только после одобрения $OWNER"
              exit 1
            fi
          else
            echo "PR от другого пользователя, ограничения не применяются"
          fi
