name: Restrict Test User Push

on:
  push:
    branches:
      - '*' # Срабатывает на все ветки

jobs:
  restrict-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check user and branch
        run: |
          USER=${{ github.actor }}  # Имя пользователя
          BRANCH_NAME=${{ github.ref_name }}  # Имя ветки

          # Проверяем, что это test
          if [ "$USER" == "Valey88" ]; then
            if [ "$BRANCH_NAME" != "frontend" ]; then
              echo "Ошибка: $USER может пушить только в ветку frontend, а не в $BRANCH_NAME"
              exit 1
            fi
            echo "Push в ветку $BRANCH_NAME разрешён для $USER"
          else
            echo "Другие пользователи могут пушить в любую ветку"
          fi
